shop/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shop.Models
{
    public class ShoppingCart
    {
        MyContext db = new MyContext();
        string ShoppingCartID { get; set; }
        public const string CartSessionKey = "CartID";
        public static ShoppingCart GetCart(HttpContextBase context)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartID = cart.GetCartID(context);
            return cart;
        }

        //Helper method to simplify shopping cart calls
        public static ShoppingCart GetCart(Controller controller)
        {
            return GetCart(controller.HttpContext);
        }

        public void AddToCart(Book book)
        {
            var cartBook = db.Carts.SingleOrDefault(
                c => c.CartID == ShoppingCartID
                && c.BookID == book.ID);

            if(cartBook == null)
            {
                cartBook = new Cart
                {
                    BookID = book.ID,
                    CartID = ShoppingCartID,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                db.Carts.Add(cartBook);
            }
            else
            {
                cartBook.Count++;
            }

            db.SaveChanges();
        }

        public int RemoveFromCart (int id)
        {
            var cartBook = db.Carts.Single(
                cart => cart.CartID == ShoppingCartID
                && cart.RecordID == id);
            int bookCount = 0;

            if(cartBook != null)
            {
                if (cartBook.Count > 1)
                {
                    cartBook.Count--;
                    bookCount = cartBook.Count;
                }
                else
                {
                    db.Carts.Remove(cartBook);
                }
                db.SaveChanges();
            }
            return bookCount;
        }

        public void EmptyCart()
        {
            var cartBooks = db.Carts.Where(
                cart => cart.CartID == ShoppingCartID);
            foreach (var cartBook in cartBooks)
            {
                db.Carts.Remove(cartBook);
            }
            db.SaveChanges();
        }

        public List<Cart> GetCartBooks()
        {
            return db.Carts.Where(
                cart => cart.CartID == ShoppingCartID).ToList();

        }

        public int GetCount()
        {
            int? count = (from cartBooks in db.Carts
                          where cartBooks.CartID == ShoppingCartID
                          select (int?)cartBooks.Count).Sum();
            return count ?? 0;
        }

        public decimal GetTotal()
        {

            decimal? total = (from cartBooks in db.Carts
                              where cartBooks.CartID == ShoppingCartID
                              select (int?)cartBooks.Count *
                              cartBooks.Book.Price).Sum();

            return total ?? decimal.Zero;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartBooks = GetCartBooks();

            foreach (var book in cartBooks)
            {
                var orderDetail = new OrderDetail
                {
                    BookID = book.BookID,
                    OrderID = order.OrderID,
                    UnitPrice = book.Book.Price,
                    Quantity = book.Count
                };

                orderTotal += (book.Count * book.Book.Price);

                db.OrderDetails.Add(orderDetail);

            }

            order.Total = orderTotal;


            db.SaveChanges();

            EmptyCart();

            return order.OrderID;
        }

        public string GetCartID(HttpContextBase context)
        {
            if (context.Session[CartSessionKey] == null)
            {
                if (!string.IsNullOrWhiteSpace(context.User.Identity.Name))
                {
                    context.Session[CartSessionKey] =
                        context.User.Identity.Name;
                }
                else
                {

                    Guid tempCartId = Guid.NewGuid();

                    context.Session[CartSessionKey] = tempCartId.ToString();
                }
            }
            return context.Session[CartSessionKey].ToString();
        }

        public void MigrateCart(string Email)
        {
            var shoppingCart = db.Carts.Where(
                c => c.CartID == ShoppingCartID);

            foreach (Cart item in shoppingCart)
            {
                item.CartID = Email;
            }
            db.SaveChanges();
        }

    }
}

shop/ViewModels/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using shop.Models;
using System.ComponentModel.DataAnnotations;

namespace shop.ViewModels
{
    public class ShoppingCartViewModel
    {
        
        public List<Cart> CartBooks { get; set; }
        public decimal CartTotal { get; set; }

    }
}

shop/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;

namespace shop.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        MyContext storeDB = new MyContext();
        const string PromoCode = "50";

        public ActionResult AddressAndPayment()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            try
            {
                if(string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.UserName = User.Identity.Name;
                    order.OrderDate = DateTime.Now;
                    

                    storeDB.Orders.Add(order);
                    storeDB.SaveChanges();

                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    cart.CreateOrder(order);

                    return RedirectToAction("Complete", new { id = order.OrderID });

                }
            }
            catch
            {
                return View(order);
            }
        }

        public ActionResult Complete(int id)
        {
            bool isValid = storeDB.Orders.Any(
                o => o.OrderID == id &&
                o.UserName == User.Identity.Name);
            if(isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
        
}

shop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;
using shop.ViewModels;

namespace shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyContext db = new MyContext();

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);


            var viewModel = new ShoppingCartViewModel
            {
                CartBooks = cart.GetCartBooks(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {

            var addedBook = db.Books
                .Single(book => book.ID == id);


            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedBook);


            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {

            var cart = ShoppingCart.GetCart(this.HttpContext);


            string bookName = db.Carts
                .Single(book => book.RecordID == id).Book.Title;


            int bookCount = cart.RemoveFromCart(id);


            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(bookName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                BookCount = bookCount,
                DeleteID = id
            };
            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

shop/Views/ShoppingCart/Index.cshtml
@model shop.ViewModels.ShoppingCartViewModel

@{

    ViewBag.Title = "Shopping Cart";

}

<script src="/Scripts/jquery-1.10.2.min.js"
        type="text/javascript"></script>

<script type="text/javascript">

    $(function () {

        // Document.ready -> link up remove event handler

        $(".RemoveLink").click(function () {

            // Get the id from the link

            var recordToDelete = $(this).attr("data-id");

            if (recordToDelete != '') {

                // Perform the ajax post

                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },

                    function (data) {

                        // Successful requests get here

                        // Update the page elements

                        if (data.BookCount == 0) {

                            $('#row-' + data.DeleteID).fadeOut('slow');

                        } else {

                            $('#book-count-' + data.DeleteID).text(data.BookCount);

                        }

                        $('#cart-total').text(data.CartTotal);

                        $('#update-message').text(data.Message);

                        $('#cart-status').text('Cart (' + data.CartCount + ')');

                    });

            }

        });

    });

</script>



<div class="container">
    <h3>
        <u>
            <em>Review</em> your cart:
        </u>
    </h3>

    <div class="col-xs-6">
        <div id="update-message">
        </div>
        <table class="table">
            <thead class="thead-inverse">
                <tr>
                    <th>Item Name</th>
                    <th>Price (each)</th>
                    <th>Quantity</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cart in Model.CartBooks)
            {
                    <tr id="row-@cart.RecordID">
                        <td>@Html.ActionLink(cart.Book.Title, "Details", "Home", new { id = cart.BookID }, null) </td>
                        <td>@cart.Book.Price</td>
                        <td id="book-count-@cart.RecordID">@cart.Count</td>
                        <td>
                            <a href="#" class="RemoveLink" data-id="@cart.RecordID">Remove from cart</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tr>
                <td>Total</td>
                <td></td>
                <td></td>
                <td id="cart-total"> @Model.CartTotal</td>
            </tr>
        </table>
    </div>
    <div class="col-xs-6">
        <br /><br />

        <p>Shipping and taxes calculated at checkout</p>
        <p class="button">
            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("AddressAndPayment", "Checkout")'">
                <span class="glyphicon glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> CHECK OUT ->
            </button>
        </p>
    </div>
</div>