shop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;
using Rotativa;

namespace shop.Controllers
{
    public class HomeController : Controller
    {
        MyContext db = new MyContext();

        public ActionResult Index()
        {   
            var categories = db.Categories.ToList();
            return View(categories);
        }

        public ActionResult SelectCategory(string category)
        {
            var selectedCategory = db.Categories.Include("Books").Single(c => c.CategoryName == category);
            return View(selectedCategory);
        }

        public ActionResult SelectCategoryForPdf(string category)
        {
            var selectedCategory = db.Categories.Include("Books").Single(c => c.CategoryName == category);
            return View(selectedCategory);
        }

        public ActionResult PDF(string category)
        {

            return new Rotativa.ActionAsPdf("SelectCategoryForPdf", new { category = category });
        }


        public ActionResult Search(string searchBy, string search)
        {
            if (searchBy == "Author")
            {
                return View(db.Books.Where(a => a.Author.Contains(search) || search == null).ToList());
            }
            if (searchBy == "Title")
            {
                return View(db.Books.Where(a => a.Title.Contains(search) || search == null).ToList());
            }
            if (searchBy == "Description")
            {
                return View(db.Books.Where(a => a.Description.Contains(search) || search == null).ToList());
            }
            if (searchBy == "Image")
            {
                return View(db.Books.Where(a => a.ItemArtUrl != null || search == null).ToList());
            }
            if (searchBy == "Price>")
            {
                decimal searchConvert = Convert.ToDecimal(search);
                return View(db.Books.Where(a => a.Price >= searchConvert || search == null).ToList());
            }
            if (searchBy == "Price<")
            {
                decimal searchConvert = Convert.ToDecimal(search);
                return View(db.Books.Where(a => a.Price <= searchConvert || search == null).ToList());
            }
            return View();
        }

        public ActionResult Details (int id)
        {
            var Book = db.Books.Find(id);
            return View(Book);
        }
        [Authorize(Roles = "admin")]
        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

shop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shop.Models;
using shop.ViewModels;

namespace shop.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyContext db = new MyContext();

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);


            var viewModel = new ShoppingCartViewModel
            {
                CartBooks = cart.GetCartBooks(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }

        public ActionResult AddToCart(int id)
        {

            var addedBook = db.Books
                .Single(book => book.ID == id);


            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedBook);


            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {

            var cart = ShoppingCart.GetCart(this.HttpContext);


            string bookName = db.Carts
                .Single(book => book.RecordID == id).Book.Title;


            int bookCount = cart.RemoveFromCart(id);


            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(bookName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                BookCount = bookCount,
                DeleteID = id
            };
            return Json(results);
        }

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

shop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/Content/Images/index-ebo.png" style="width:100%" class="img-responsive">
            <div class="container">
                <div class="carousel-caption" style="padding-bottom:220px">
                    <div class="row">
                        <div class="row">
                            <div class="col-md-8">
                                <h2 style="color:#3C3C3C">About Us ...</h2>
                                <h4 style="color:#3C3C3C">
                                    Some people like to read on a screen. Other people need the variety and artistry, the sight, smell, and feel of actual books.They love seeing them on their shelves; they love having shelves for them.
                                    They want to read in a way that offers a rich experience, more than the words only: the full offering of a book. They are particular about covers, they want to surround themselves with the poetry of good design.
                                    These are the people we're working for.
                                </h4>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

shop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}



<section id="contact">
    <div class="container">
        <div class="well well-sm">
            <h3><strong>Contact Us</strong></h3>
        </div>

        <div class="row">
            <div class="col-md-7">
                <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d3736489.7218514383!2d90.21589792292741!3d23.857125486636733!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1506502314230" width="100%" height="315" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <div class="col-md-5">
                <address>
                    VP Gr.<br />
                    Redmond, WA 98052-6399<br />
                    <abbr title="Phone">P:</abbr>
                    425.555.0100
                </address>

                <address>
                    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
                    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
                </address>
            </div>
        </div>
    </div>
</section>

shop/Views/Home/Details.cshtml
@model shop.Models.Book

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <center>
        <h2><u>BOOKS</u></h2>
    </center>
    <div class="row">
        <div class="col-xs-6">
            <div class="text-center">
                <img class="img-rounded" src="@Model.ItemArtUrl" alt="Generic placeholder image" width="450" height="500">
            </div>
            <div class="row">
                <div class="col-md-4 thumb">
                    <center>
                        <a class="fancyimage" rel="group" href="@Model.ItemArtUrl_1">
                            <img class="img-responsive" src="@Model.ItemArtUrl_1" />
                        </a>
                    </center>
                </div>
                <div class="col-md-4 thumb">
                    <center>
                        <a class="fancyimage" rel="group" href="@Model.ItemArtUrl_2">
                            <img class="img-responsive" src="@Model.ItemArtUrl_2" />
                        </a>
                    </center>
                </div>
            </div>
        </div>

        <div class="col-xs-6">
            <center>
                <h2>@Model.Author</h2>
                <h4>@Model.Title</h4>
                <h4>@Model.Price $</h4>

                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("AddToCart", "ShoppingCart", new { id = Model.ID })'">
                    <span class="glyphicon glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Add to cart
                </button>
                <h4>___________________</h4>
                <h4>@Model.Description</h4>
            </center>
        </div>
    </div>
</div>

shop/Views/Home/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
<div class="container">
    <h2>Edit</h2>
    <ul>
        <li>
            <a href="~/BooksManager/Index">Books</a>
        </li>
        <li>
            <a href="~/CategoriesManager/Index">Categories</a>
        </li>
        <li>
            <a href="~/OrdersManager/Index">Orders</a>
        </li>
        <li>
            <a href="~/UsersManager/Index">Users</a>
        </li>
    </ul>
</div>

shop/Views/Home/Index.cshtml
@model IEnumerable<shop.Models.Category>

@{
    ViewBag.Title = "Shop";
}

<div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
        <div class="item active">
            <img src="~/Content/Images/index_sl.png" style="width:100%" class="img-responsive">
            <div class="container">
                <div class="carousel-caption" style="padding-bottom:150px">
                    <div class="row">
                        <div class="col-md-9 col-md-push-3">

                        </div>
                        <div class="col-md-3 col-md-pull-9 ">
                            <ul class="list-group">
                                @foreach (var category in Model)
                                {
                                    <li class="list-group-item list-group-item-dark">@Html.ActionLink(category.CategoryName, "SelectCategory", new { category = category.CategoryName })</li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br /><br /><br />
<div class="container">
    <center>

        @using (Html.BeginForm("Search", "Home", FormMethod.Get))
        {
            <b>Search By: </b>
            <button type="button" class="btn btn-secondary">
                @Html.RadioButton("searchBy", "Author", true) <text>Author</text>
            </button>
            @Html.RadioButton("searchBy", "Title") <text>Title</text>
            @Html.RadioButton("searchBy", "Description") <text>Description</text>
            @Html.RadioButton("searchBy", "Image") <text>Image Exists</text>
            @Html.RadioButton("searchBy", "Price>") <text>Price is equal or higher </text>
            @Html.RadioButton("searchBy", "Price<") <text>Price is equal or lower </text>
            <br />
            @Html.TextBox("search") <input type="submit" value="Search" />
        }
    </center>
    <br /><br /><br />
    <center>
        <p>Total Number of visitors: @ApplicationInstance.Application["Totaluser"]</p>
    </center>
</div>

shop/Views/Home/Search.cshtml
@model IEnumerable<shop.Models.Book>
@{
    ViewBag.Title = "Search";
}

<div class="container">
    <h2>Results</h2>
    @if (Model.Count() == 0)
    {
        <div class="alert alert-danger" role="alert">
            <h3>We are sorry, but no rows match search criteria</h3>
        </div>

    }
    else
    {
        <div class="row" style="margin-top:50px;">
            @foreach (var book in Model)
            {
                <div class="col-xs-3 vcenter">
                    <center>
                        <img class="img-rounded" src="@book.ItemArtUrl" alt="Generic placeholder image" width="140" height="140">
                    </center>
                    <h4> Autor: @book.Author</h4>
                    <h4>Title: @book.Title</h4>
                    <h4>Price: @book.Price $</h4>
                    <p><a class="btn btn-default" href="@Url.Action("Details", new { id = book.ID })" role="button">View details &raquo;</a></p>
                </div>
            }
        </div>
    }
</div>

shop/Views/Home/SelectCategory.cshtml
@model shop.Models.Category

@{
    ViewBag.Title = "SelectCategory";
}

<div class="container">
    <center>
        <h2><u> Category: @Model.CategoryName</u></h2>
    </center>
    @Html.ActionLink("Generate PDF", "PDF", new { category = Model.CategoryName })

    <div class="row" style="margin-top:50px;">
        @foreach (var book in Model.Books)
            {
            <div class="col-xs-3 vcenter">
                <center>
                    <img class="img-rounded" src="@book.ItemArtUrl" alt="Generic placeholder image" width="140" height="140">
                </center>
                <h4> Autor: @book.Author</h4>
                <h4>Title: @book.Title</h4>
                <h4>Price: @book.Price $</h4>
                <p><a class="btn btn-default" href="@Url.Action("Details", new { id = book.ID })" role="button">View details &raquo;</a></p>
            </div>
        }
    </div>
</div>

shop/Views/Home/SelectCategoryForPdf.cshtml
@model shop.Models.Category

@{
    ViewBag.Title = "SelectCategory";
}

<h2>Category: @Model.CategoryName</h2>



<table class="table">
    <tr>
        <th>
            Image
        </th>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Price
        </th>
    </tr>

    @foreach (var item in Model.Books)
    {
        <tr>
            <td>
                <img class="img-rounded" src="@item.ItemArtUrl" alt="Generic placeholder image" width="140" height="140">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td> 
        </tr>
    }

</table>